/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "implementation-test.check" instead.
 */

#include <check.h>

#line 1 "implementation-test.check"
#include "implementation.h"
#include<stdio.h>
//#include <check.h>

int a[5]={5,4,3,2,1},pos,i,n=5;

START_TEST(sum2test)
{
#line 8
	pos=partition(a, 5);
	for(i=0;i<pos;i++)
	ck_assert_int_le (a[i],a[pos]);
	for(i=pos+1; i<n; i++)
	ck_assert_int_le (a[pos],a[i]);		
	
	
	
	   
/*	fail_unless(sum(-3, 2) == -1, "sum function forked");
	fail_unless(sum(3, -2) == 1, "sum function forked");
	fail_unless(sum(-3, -2) == -5, "sum function forked");*/
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, sum2test);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
